url: https://goodyduru.github.io/
theme: jekyll-theme-architect
title: Goodness's blog
author: Goodness Duru
description: A place where I riff on my current projects.
twitter_username: goodyduru
github_username: goodyduru
email: goodyduru@gmail.com
show_excerpts: true
