baseURL = 'https://goodyduru.com/'
languageCode = 'en-us'
title = 'Goodness Duru'
theme = 'rocinante'
[markup]
  [markup.highlight]
    tabWidth = 2
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true
[params]
  colorScheme = "auto"
  customCSS = []
  favicon = ""
  socialBanner = ""
  mainSections = ["posts"]
  email = "goodyduru@gmail.com"
  about = """
Hey person or bot 🌚 on the internet. I'm Goodness.

Welcome to my site on the net. You're free to explore every nook and cranny.

I'm a generalist software engineer who is curious about the entire stack. My writings tend to be the final stage of what I've learnt.

Email me if you'd like to _chat_ or work together.
<br>
"""

[[params.links]]
  [[params.links.link]]
  name = "Projects"
  href = "/projects"
  [[params.links.link]]
  name = "TILs"
  href = "/tils"
  [[params.links.link]]
  name = "Resume"
  href = "/resume.pdf"
  new_tab = true
  [[params.links.link]]
  name = "Email"
  href = "/contact"
  smart_email_link = true
  [[params.links.link]]
  name = "Github"
  href = "https://github.com/goodyduru"
  new_tab = true
  [[params.links.link]]
  name = "LinkedIn"
  href = "https://www.linkedin.com/in/goodyduru/"
  new_tab = true

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
